module.exports=(sequelize,DataTypes)=>{
    const carstable=sequelize.define("carstable",{
        username:{
            type:DataTypes.STRING,
            allowNull:false
        },
        brand:{
            type:DataTypes.STRING,
            allowNull:false
        },
        model:{
            type:DataTypes.STRING,
            allowNull:false
        },
        description:{
            type:DataTypes.STRING,
            allowNull:false
        },
        price:{
            type:DataTypes.STRING,
            allowNull:true
        },
        compartment:{
            type:DataTypes.STRING,
            allowNull:false
        },
        eurostandart:{
            type:DataTypes.STRING,
            allowNull:true
        },
        engine:{
            type:DataTypes.STRING,
            allowNull:false
        },
        transmission:{
            type:DataTypes.STRING,
            allowNull:false
        },
        manafacture:{
            type:DataTypes.STRING,
            allowNull:false
        },
        mileage:{
            type:DataTypes.STRING,
            allowNull:false
        },
        power:{
            type:DataTypes.STRING,
            allowNull:true
        },
        doors:{
            type:DataTypes.STRING,
            allowNull:false
        },
        phoneNumber:{
            type:DataTypes.STRING,
            allowNull:true
        }
    })
    return carstable
}  