
module.exports=(sequelize,DataTypes) =>{
    const jobstable=sequelize.define("jobstable",{
        username:{
            type:DataTypes.STRING,
            allowNull:false
        },
            title:{
                type:DataTypes.STRING,
                allowNull:false
            },
            textDescription:{
                type:DataTypes.STRING,
                allowNull:false
            },
            phoneNumber:{
                type:DataTypes.STRING,
                allowNull:true
            },
            salary:{
                type:DataTypes.STRING,
                allowNull:true
            },
            location:{
                type:DataTypes.STRING,
                allowNull:false
            },
            position:{
                type:DataTypes.STRING,
                allowNull:true
            }, 
            education:{
                type:DataTypes.STRING,
                allowNull:true
            },
            employment:{
                type:DataTypes.STRING,
                allowNull:false
            }, 
            contractType:{ 
                type:DataTypes.STRING,
                allowNull:false
            },
            image1:{ 
                type:DataTypes.STRING,
                allowNull:true
            }, 
            image2:{
                type:DataTypes.STRING,
                allowNull:true
            },image3:{
                type:DataTypes.STRING,
                allowNull:true
            },image4:{
                type:DataTypes.STRING,
                allowNull:true
            },image5:{
                type:DataTypes.STRING,
                allowNull:true
            }
    })
    return jobstable;
}    